version: '3.9'
services: 
  apso:
    container_name: apso
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db_apso
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=isai
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_apso:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=isai
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db_apso:
    container_name: db_apso
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isai
      POSTGRES_DB: postgres